import json


def parse_chunks(chunks):
    """Extract prompt and parameters from NovelAI PNG metadata format."""
    prompt = ""
    neg_prompt = ""
    comment = None

    if "Comment" in chunks:
        try:
            comment = json.loads(chunks["Comment"])
        except (json.JSONDecodeError, ValueError):
            comment = None

    if "Description" in chunks:
        prompt = chunks["Description"].strip()

    if not prompt:
        if comment and comment.get("prompt"):
            prompt = comment["prompt"]
        elif "Comment" in chunks:
            prompt = chunks["Comment"].strip()

    steps = ""
    sampler = ""
    cfg_scale = ""
    seed = ""
    if comment:
        neg_prompt = comment.get("uc", "")
        steps = _as_str(comment.get("steps"))
        sampler = _as_str(comment.get("sampler"))
        cfg_scale = _as_str(comment.get("scale"))
        seed = _as_str(comment.get("seed"))

    return {
        "prompt": prompt,
        "negative_prompt": neg_prompt,
        "model": _detect_model(chunks),
        "steps": steps,
        "sampler": sampler,
        "cfg_scale": cfg_scale,
        "seed": seed,
        "size": "",
        "model_hash": "",
        "version": "",
        "loras": [],
    }


def _detect_model(chunks):
    """NovelAI images are generated by the NovelAI tool, so expose it as the model."""
    software = chunks.get("Software", "").strip()
    if software.lower().startswith("novelai"):
        return "NovelAI"
    return chunks.get("Source", "").strip()


def _as_str(value):
    if value is None or isinstance(value, bool):
        return ""
    return str(value)
